import { Router } from 'express';
import { authMiddleware } from '../middleware/auth.js';
import { ensureAuthenticated } from '../lib/panelClient.js';
import { buildProtocolSummary, canonicalizeProtocolList } from '../lib/protocolCatalog.js';

const router = Router();

const TOOL_CAPABILITIES = [
    {
        key: 'uuid',
        label: 'UUID',
        description: 'Generate VMess/VLESS UUID values from the node panel.',
        path: '/panel/api/server/getNewUUID',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'x25519',
        label: 'X25519',
        description: 'Generate X25519 keys for REALITY transport settings.',
        path: '/panel/api/server/getNewX25519Cert',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'mldsa65',
        label: 'ML-DSA-65',
        description: 'Generate ML-DSA-65 material for modern 3x-ui node crypto flows.',
        path: '/panel/api/server/getNewmldsa65',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'mlkem768',
        label: 'ML-KEM-768',
        description: 'Generate ML-KEM-768 key material from the node panel.',
        path: '/panel/api/server/getNewmlkem768',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'vlessEnc',
        label: 'VLESS Enc',
        description: 'Generate VLESS encryption material supported by the node panel.',
        path: '/panel/api/server/getNewVlessEnc',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'echCert',
        label: 'ECH Cert',
        description: 'Generate ECH certificates when the node exposes the helper endpoint.',
        path: '/panel/api/server/getNewEchCert',
        method: 'post',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'panelLogs',
        label: 'Panel Logs',
        description: 'Read panel logs from nodes that expose the 3x-ui log endpoint.',
        path: '/panel/api/server/logs/20',
        method: 'post',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Home',
        uiAction: 'logs',
        uiActionLabel: '日志中心',
        supportedByNms: true,
    },
    {
        key: 'panelUpdateInfo',
        label: 'Panel Update Info',
        description: 'Inspect current and latest panel versions before maintenance.',
        path: '/panel/api/server/getPanelUpdateInfo',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'xrayMetricsState',
        label: 'Xray Metrics State',
        description: 'Inspect runtime metrics collection state exposed by recent 3x-ui builds.',
        path: '/panel/api/server/xrayMetricsState',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'xrayObservatory',
        label: 'Xray Observatory',
        description: 'Inspect observatory probe results exposed by recent 3x-ui builds.',
        path: '/panel/api/server/xrayObservatory',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'customGeoResources',
        label: 'Custom Geo Resources',
        description: 'Legacy custom GeoIP / GeoSite resources from pre-3.3.1 3x-ui builds.',
        path: '/panel/api/custom-geo/list',
        method: 'get',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        uiAction: 'docs_only',
        uiActionLabel: '官方文档',
        supportedBy3xui: false,
        supportedByNms: false,
        status: 'removed_upstream',
        note: '3x-ui v3.3.1 replaced the custom geo manager with native Xray-core geodata auto-update.',
    },
    {
        key: 'xrayLogs',
        label: 'Xray Logs',
        description: 'Read xray logs from nodes that expose the xray log endpoint.',
        path: '/panel/api/server/xraylogs/20',
        method: 'post',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Home',
        uiAction: 'logs',
        uiActionLabel: '日志中心',
        supportedByNms: true,
    },
    {
        key: 'apiLogin',
        label: 'API Login',
        description: 'Login authentication session and cookie setup.',
        path: '/login',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/login.mdx',
        uiAction: 'login',
        uiActionLabel: '登录页',
        supportedByNms: true,
    },
    {
        key: 'inboundList',
        label: 'Get Inbounds List',
        description: 'Retrieve all configured inbounds from the active panel.',
        path: '/panel/api/inbounds/list',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundGet',
        label: 'Get Inbound Detail',
        description: 'Retrieve a specific inbound details using its ID.',
        path: '/panel/api/inbounds/get/:id',
        method: 'get',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundAdd',
        label: 'Add Inbound',
        description: 'Create a new inbound protocol setup on the node.',
        path: '/panel/api/inbounds/add',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundUpdate',
        label: 'Update Inbound',
        description: 'Modify settings for an existing inbound connection.',
        path: '/panel/api/inbounds/update/:id',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundDel',
        label: 'Delete Inbound',
        description: 'Remove an inbound connection from the panel core.',
        path: '/panel/api/inbounds/del/:id',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundOnlines',
        label: 'Inbound Online Status',
        description: 'Fetch online client IP counts categorized under active inbounds.',
        path: '/panel/api/inbounds/onlines',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/inbounds.mdx',
        uiAction: 'inbounds',
        uiActionLabel: '入站管理',
        supportedByNms: true,
    },
    {
        key: 'inboundAddClient',
        label: 'Add Client (Legacy)',
        description: 'Attach a client to an inbound configuration using standard forms.',
        path: '/panel/api/inbounds/addClient',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'inboundUpdateClient',
        label: 'Update Client (Legacy)',
        description: 'Update client specifications linked to a single inbound.',
        path: '/panel/api/inbounds/updateClient/:uuid',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'inboundDelClient',
        label: 'Delete Client (Legacy)',
        description: 'Detach or remove a client record from a legacy inbound.',
        path: '/panel/api/inbounds/delClient/:id',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'inboundClientIps',
        label: 'Client IPs (Legacy)',
        description: 'Retrieve logged connection IPs for a client email on legacy panels.',
        path: '/panel/api/inbounds/clientIps/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'inboundClearClientIps',
        label: 'Clear Client IPs (Legacy)',
        description: 'Clear recorded connection IP history for an email on legacy panels.',
        path: '/panel/api/inbounds/clearClientIps/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientAdd',
        label: 'Add Client (V3)',
        description: 'Add a new client globally and map to multiple inbounds at once.',
        path: '/panel/api/clients/add',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientUpdate',
        label: 'Update Client (V3)',
        description: 'Modify parameters for a client across all associated inbounds.',
        path: '/panel/api/clients/update/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientDel',
        label: 'Delete Client (V3)',
        description: 'Permanently remove a client globally from all node configurations.',
        path: '/panel/api/clients/del/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientGet',
        label: 'Get Client Detail (V3)',
        description: 'Retrieve a global client record and inbound mapping by email.',
        path: '/panel/api/clients/get/:email',
        method: 'get',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientOnlines',
        label: 'Global Online Clients (V3)',
        description: 'List all currently connected clients across the entire panel.',
        path: '/panel/api/clients/onlines',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'dashboard',
        uiActionLabel: '控制面板',
        supportedByNms: true,
    },
    {
        key: 'v3ClientOnlinesByGuid',
        label: 'Onlines By GUID (V3)',
        description: 'Query active connections grouped by server GUID.',
        path: '/panel/api/clients/onlinesByGuid',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'dashboard',
        uiActionLabel: '控制面板',
        supportedByNms: true,
    },
    {
        key: 'v3ClientOnlinesByNode',
        label: 'Onlines By Node (V3)',
        description: 'Query active connections grouped by node parameters.',
        path: '/panel/api/clients/onlinesByNode',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'dashboard',
        uiActionLabel: '控制面板',
        supportedByNms: true,
    },
    {
        key: 'v3ClientLastOnline',
        label: 'Last Online Stats (V3)',
        description: 'Fetch last observed connection timestamps for all clients.',
        path: '/panel/api/clients/lastOnline',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'dashboard',
        uiActionLabel: '控制面板',
        supportedByNms: true,
    },
    {
        key: 'v3ClientIps',
        label: 'Client IPs (V3)',
        description: 'Retrieve logged connection IPs for a client email globally.',
        path: '/panel/api/clients/ips/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientClearIps',
        label: 'Clear Client IPs (V3)',
        description: 'Clear recorded connection IP history globally for an email.',
        path: '/panel/api/clients/clearIps/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientAttach',
        label: 'Attach Client (V3)',
        description: 'Bind an existing client email to additional inbounds.',
        path: '/panel/api/clients/:email/attach',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientDetach',
        label: 'Detach Client (V3)',
        description: 'Unbind a client email from specific inbounds without deleting.',
        path: '/panel/api/clients/:email/detach',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientBulkAdjust',
        label: 'Bulk Adjust Clients (V3)',
        description: 'Add bytes or days dynamically in bulk to selected client emails.',
        path: '/panel/api/clients/bulkAdjust',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'v3ClientResetTraffic',
        label: 'Reset Client Traffic (V3)',
        description: 'Reset accumulated traffic counter to 0 for a specific client email.',
        path: '/panel/api/clients/resetTraffic/:email',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/clients.mdx',
        uiAction: 'clients',
        uiActionLabel: '用户管理',
        supportedByNms: true,
    },
    {
        key: 'serverStatus',
        label: 'Server Status Metrics',
        description: 'Retrieve real-time server system metrics (RAM, CPU, traffic stats).',
        path: '/panel/api/server/status',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'xrayVersionGet',
        label: 'Get Xray Versions',
        description: 'Get current Xray core version and list available releases.',
        path: '/panel/api/server/getXrayVersion',
        method: 'get',
        probe: true,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'xrayInstall',
        label: 'Install Xray Core',
        description: 'Install or switch to a target version of Xray-core.',
        path: '/panel/api/server/installXray/:version',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'xrayRestart',
        label: 'Restart Xray Service',
        description: 'Restart the xray-core binary process on the node panel.',
        path: '/panel/api/server/restartXray',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'dbExport',
        label: 'Export Database',
        description: 'Download the configuration sqlite db file from the panel.',
        path: '/panel/api/server/database/export',
        method: 'get',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'dbImport',
        label: 'Import Database',
        description: 'Upload and restore the configuration sqlite db file to the panel.',
        path: '/panel/api/server/database/import',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'geofileUpdate',
        label: 'Update Geofiles',
        description: 'Trigger download of latest GeoIP and GeoSite files.',
        path: '/panel/api/server/geofile/update',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
    {
        key: 'telegramBackupTrigger',
        label: 'Trigger Telegram Backup',
        description: 'Send current database snapshot to the configured Telegram bot Channel.',
        path: '/panel/api/server/telegram/backup',
        method: 'post',
        probe: false,
        docs: 'https://github.com/MHSanaei/3x-ui-docs/blob/main/content/docs/zh/reference/api/server.mdx',
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        supportedByNms: true,
    },
];

async function detectToolCapabilities(client) {
    const checks = await Promise.all(TOOL_CAPABILITIES.map(async (tool) => {
        if (tool.supportedBy3xui === false) {
            return { ...tool, available: false, source: 'upstream_removed' };
        }
        if (!tool.probe) {
            return { ...tool, available: null, source: 'unprobed' };
        }

        try {
            await client({
                method: tool.method,
                url: tool.path,
                timeout: 10000,
            });
            return { ...tool, available: true, source: 'probed' };
        } catch {
            return { ...tool, available: false, source: 'probed' };
        }
    }));

    return checks.reduce((acc, item) => {
        acc[item.key] = {
            key: item.key,
            label: item.label,
            description: item.description,
            path: item.path,
            method: item.method,
            docs: item.docs,
            uiAction: item.uiAction,
            uiActionLabel: item.uiActionLabel,
            supportedBy3xui: item.supportedBy3xui !== false,
            supportedByNms: item.supportedByNms === true,
            status: item.status || (item.supportedByNms === true ? 'integrated' : 'api_available_ui_missing'),
            available: item.available,
            source: item.source,
            note: item.note || '',
        };
        return acc;
    }, {});
}

const SYSTEM_MODULES = [
    {
        key: 'xrayVersion',
        label: 'Xray Version Management',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Version list, install, and restart are exposed from the node control console.',
    },
    {
        key: 'xrayConfig',
        label: 'Xray Config Viewer',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'NMS can open the current node config but does not edit private template internals.',
    },
    {
        key: 'xrayRouting',
        label: 'Xray Routing / Outbounds / DNS',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'xray_console',
        uiActionLabel: 'Xray 设置',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Routing rules, outbounds, DNS and balancers are editable from the Xray console.',
    },
    {
        key: 'twoFactor',
        label: 'Admin 2FA (TOTP)',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'account',
        uiActionLabel: '账户中心',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki',
        note: 'Per-admin TOTP with backup codes managed from the account center.',
    },
    {
        key: 'databaseManagement',
        label: 'Database Management',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Export and import are supported on single-node scope only.',
    },
    {
        key: 'geofile',
        label: 'Geofile Update',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'GeoIP and GeoSite update actions are integrated.',
    },
    {
        key: 'telegramBackup',
        label: 'Telegram Backup',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'NMS can trigger backup, but Telegram bot settings still stay in the panel.',
    },
    {
        key: 'panelSelfUpdate',
        label: 'Panel Self Update',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Current and latest panel versions are exposed through node tools for maintenance checks.',
    },
    {
        key: 'xrayRuntimeMetrics',
        label: 'Xray Runtime Metrics',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'node_console',
        uiActionLabel: '节点控制台',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Recent 3x-ui metric and observatory payloads are available from node tools.',
    },
    {
        key: 'telegramBot',
        label: 'Telegram Bot Settings',
        status: 'integrated',
        supportedBy3xui: true,
        supportedByNms: true,
        uiAction: 'system_settings',
        uiActionLabel: '系统设置',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'NMS can configure Telegram alerts and accepts low-risk bot commands from system settings.',
    },
    {
        key: 'panelWebBasePath',
        label: 'Panel Web Base Path',
        status: 'guided_only',
        supportedBy3xui: true,
        supportedByNms: false,
        uiAction: 'panel_only',
        uiActionLabel: '3x-ui 面板',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Configuration',
        note: 'Kept as guided-only until a reliable admin workflow is added to NMS.',
    },
    {
        key: 'panelCertificatePath',
        label: 'Panel Certificate Paths',
        status: 'guided_only',
        supportedBy3xui: true,
        supportedByNms: false,
        uiAction: 'panel_only',
        uiActionLabel: '3x-ui 面板',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/SSL-Certificate',
        note: 'Certificate path writes remain a panel-side workflow for now.',
    },
    {
        key: 'cloudflareWarp',
        label: 'Cloudflare WARP',
        status: 'guided_only',
        supportedBy3xui: true,
        supportedByNms: false,
        uiAction: 'docs_only',
        uiActionLabel: '官方文档',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Cloudflare-WARP',
        note: 'High-risk network changes stay documentation-guided in NMS.',
    },
    {
        key: 'fail2ban',
        label: 'Fail2Ban',
        status: 'guided_only',
        supportedBy3xui: true,
        supportedByNms: false,
        uiAction: 'docs_only',
        uiActionLabel: '官方文档',
        docs: 'https://github.com/MHSanaei/3x-ui/wiki/Fail2ban',
        note: 'System-level hardening is intentionally left to node operators.',
    },
];

function buildCapabilitiesPayload({
    serverId,
    status,
    inbounds = [],
    xrayVersions = [],
    tools = {},
}) {
    const protocols = canonicalizeProtocolList(
        (Array.isArray(inbounds) ? inbounds : []).map((item) => item?.protocol)
    ).sort();

    return {
        serverId,
        generatedAt: new Date().toISOString(),
        status: status || null,
        protocols,
        protocolDetails: protocols.map((item) => buildProtocolSummary(item)),
        versions: {
            xray: Array.isArray(xrayVersions) ? xrayVersions : [],
        },
        tools,
        systemModules: SYSTEM_MODULES,
        batchActions: {
            clients: ['add', 'update', 'enable', 'disable', 'delete'],
            inbounds: ['add', 'update', 'enable', 'disable', 'delete', 'resetTraffic'],
        },
        nodeGovernance: {
            fields: ['group', 'tags', 'environment', 'health'],
            environments: ['production', 'staging', 'development', 'testing', 'dr', 'sandbox', 'unknown'],
            healthStates: ['unknown', 'healthy', 'degraded', 'unreachable', 'maintenance'],
        },
        subscriptionModes: ['auto', 'native', 'reconstructed'],
    };
}

router.use(authMiddleware);

router.get('/:serverId', async (req, res) => {
    try {
        const { serverId } = req.params;
        const client = await ensureAuthenticated(serverId);

        const [statusRes, inboundsRes, xrayVersionRes, tools] = await Promise.all([
            client.get('/panel/api/server/status').catch(() => null),
            client.get('/panel/api/inbounds/list').catch(() => null),
            client.get('/panel/api/server/getXrayVersion').catch(() => null),
            detectToolCapabilities(client),
        ]);

        return res.json({
            success: true,
            obj: buildCapabilitiesPayload({
                serverId,
                status: statusRes?.data?.obj || null,
                inbounds: inboundsRes?.data?.obj || [],
                xrayVersions: xrayVersionRes?.data?.obj || [],
                tools,
            }),
        });
    } catch (error) {
        if (String(error.message || '').toLowerCase().includes('server not found')) {
            return res.status(404).json({
                success: false,
                msg: '节点不存在，请刷新节点列表后重试',
            });
        }
        return res.status(500).json({
            success: false,
            msg: '节点能力探测失败，请确认节点在线并重试',
        });
    }
});

export default router;
export {
    buildCapabilitiesPayload,
    detectToolCapabilities,
};
